print('Hola ' + "Antonio")
print('Hola' + " Antonio")
print('Hola' + " " + "Antonio")
print('Me llamo \"Antonio\"')
print("Esta es una linea\nY esta es otra linea")
print("\tEsta es la tercera linea")
print('This isn\'t a number')
print('Este signo \\ es una barra invertida')
print('Barra normal: /\nBarra invertida: \\')